version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: conllu-backend
    ports:
      - "5003:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: conllu-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: conllu-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
